syms a b omega0 t omegaM g f nbar;

lambdael = exp(-1j*((b-1) - (a-1))*(1-f)*(omega0*t)) * ...
        exp(1j* (g*(1-2*f)/omegaM)^2 * ((b-1)^2 - (a-1)^2) * (omegaM*t - sin(omegaM*t))^2 ) * ...
        exp(1j* (g*(1-2*f)/omegaM)^2 * ((b-1) - (a-1)) * nbar * sin(omegaM*t)) * ...
        exp(...
              (g*(1-2*f)/omegaM)^2 * ...
              ( ...
                 ((b-1)-((b-1)-nbar)*exp(-1j*omegaM*t)) * ((a-1)-((a-1)-nbar)*exp(1j*omegaM*t)) ...
                  - 0.5*((b-1) - ((b-1)-nbar)*exp(-1j*omegaM*t)) * ((b-1) - ((b-1)-nbar)*exp(1j*omegaM*t)) ...
                  - 0.5*((a-1) - ((a-1)-nbar)*exp(-1j*omegaM*t)) * ((a-1) - ((a-1)-nbar)*exp(1j*omegaM*t))... 
               ) ...
           );
lambdaprim = diff(lambdael, f)
